language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
    - composer self-update || true
    - composer install --dev --no-interaction

script:
    - phpunit --coverage-text

notifications:
    email:
        - github@h4cc.de